- platform: template
  sensors:
    vacuum_status:
      friendly_name: Trạng Thái Bé Giúp Việc
      entity_id:
        - vacuum.be_giup_viec
      value_template: '{{ states.vacuum.be_giup_viec.attributes.status }}'
      icon_template: >
        {% set val =  states.vacuum.be_giup_viec.attributes.status  %}
        {% if val == 'Charging' %}
          mdi:battery-charging
        {% elif val == 'Cleaning' %}
          mdi:move-resize
        {% elif val == 'Returning home' %}
          mdi:keyboard-return
        {% elif val == 'Idle' %}
          mdi:dots-horizontal
        {% elif val == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan_speed:
      friendly_name: Chế độ hút bụi
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Chế độ: {{ states.vacuum.be_giup_viec.attributes.fan_speed }}'
      icon_template: 'mdi:speedometer'
    vacuum_battery:
      friendly_name: Pin bé giúp việc
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Pin: {{ states.vacuum.be_giup_viec.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: '{{ states.vacuum.be_giup_viec.attributes.battery_icon }}'
    vacuum_cleaning_time:
      friendly_name: Thời gian quét
      unit_of_measurement: 'm'
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Thời gian quét: {{ states.vacuum.be_giup_viec.attributes.cleaning_time }}'
      icon_template: 'mdi:timer'
    vacuum_cleaned_area:
      friendly_name: Diện tích quét
      unit_of_measurement: 'm ²'
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Diện tích: {{ states.vacuum.be_giup_viec.attributes.cleaned_area }}'
      icon_template: 'mdi:ruler'
    vacuum_cleanmainbrush:
      friendly_name: Chổi chính
      unit_of_measurement: 'h'
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Chổi chính: {{ states.vacuum.be_giup_viec.attributes.main_brush_left }}'
      icon_template: 'mdi:screwdriver'
    vacuum_cleansidebrush:
      friendly_name: Chổi phụ
      unit_of_measurement: 'h'
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Chổi phụ: {{ states.vacuum.be_giup_viec.attributes.side_brush_left }}'
      icon_template: 'mdi:screwdriver'
    vacuum_cleanfilter:
      friendly_name: Bộ lọc bụi
      unit_of_measurement: 'h'
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Màng lọc: {{ states.vacuum.be_giup_viec.attributes.filter_left }}'
      icon_template: 'mdi:screwdriver'
    vacuum_sensordirtyleft:
      friendly_name: Cảm biến
      unit_of_measurement: 'h'
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'Cảm biến: {{ states.vacuum.be_giup_viec.attributes.sensor_dirty_left }}'
      icon_template: 'mdi:screwdriver'
    vacuum_do_not_disturb:
      friendly_name: Không làm phiền
      entity_id:
        - vacuum.be_giup_viec
      value_template: 'disturb: {{ states.vacuum.be_giup_viec.attributes.do_not_disturb }}'
      icon_template: >
        {% set val =  states.vacuum.be_giup_viec.attributes.do_not_disturb  %}
        {% if val == 'on' %}
          mdi:do-not-disturb
        {% else %}
          mdi:do-not-disturb-off
        {% endif %}
    vacuum_operation:
      value_template: 'Operation'
    vacuum_accessories:
      value_template: 'Maintenance'